// @generated by protobuf-ts 2.9.4 with parameter add_pb_suffix,long_type_string,optimize_code_size
// @generated from protobuf file "bookStore.proto" (package "bookStorePackage", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Our BookItem message definition.
 *
 * @generated from protobuf message bookStorePackage.BookItem
 */
export interface BookItem {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string book = 2;
     */
    book: string;
}
/**
 * Our BookRequest message definition.
 *
 * @generated from protobuf message bookStorePackage.BookRequest
 */
export interface BookRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * Our BooksList message definition. This will be an array of BookItem.
 *
 * @generated from protobuf message bookStorePackage.BooksList
 */
export interface BooksList {
    /**
     * @generated from protobuf field: repeated bookStorePackage.BookItem books = 1;
     */
    books: BookItem[];
}
/**
 * the method `readBooks` does not accept any parameter so we have to specify that it is empty.
 *
 * @generated from protobuf message bookStorePackage.Empty
 */
export interface Empty {
}
// @generated message type with reflection information, may provide speed optimized methods
class BookItem$Type extends MessageType<BookItem> {
    constructor() {
        super("bookStorePackage.BookItem", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "book", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bookStorePackage.BookItem
 */
export const BookItem = new BookItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BookRequest$Type extends MessageType<BookRequest> {
    constructor() {
        super("bookStorePackage.BookRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bookStorePackage.BookRequest
 */
export const BookRequest = new BookRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BooksList$Type extends MessageType<BooksList> {
    constructor() {
        super("bookStorePackage.BooksList", [
            { no: 1, name: "books", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => BookItem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bookStorePackage.BooksList
 */
export const BooksList = new BooksList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Empty$Type extends MessageType<Empty> {
    constructor() {
        super("bookStorePackage.Empty", []);
    }
}
/**
 * @generated MessageType for protobuf message bookStorePackage.Empty
 */
export const Empty = new Empty$Type();
/**
 * @generated ServiceType for protobuf service bookStorePackage.BookService
 */
export const BookService = new ServiceType("bookStorePackage.BookService", [
    { name: "createBook", options: {}, I: BookItem, O: BookItem },
    { name: "readBook", options: {}, I: BookRequest, O: BookItem },
    { name: "readBooks", options: {}, I: Empty, O: BooksList }
]);
