// @generated by protobuf-ts 2.9.4 with parameter add_pb_suffix,long_type_string,optimize_code_size
// @generated from protobuf file "bookStore.proto" (package "bookStorePackage", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BookService } from "./bookStore_pb";
import type { BooksList } from "./bookStore_pb";
import type { Empty } from "./bookStore_pb";
import type { BookRequest } from "./bookStore_pb";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BookItem } from "./bookStore_pb";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Our Book service definition.
 *
 * @generated from protobuf service bookStorePackage.BookService
 */
export interface IBookServiceClient {
    /**
     * @generated from protobuf rpc: createBook(bookStorePackage.BookItem) returns (bookStorePackage.BookItem);
     */
    createBook(input: BookItem, options?: RpcOptions): UnaryCall<BookItem, BookItem>;
    /**
     * @generated from protobuf rpc: readBook(bookStorePackage.BookRequest) returns (bookStorePackage.BookItem);
     */
    readBook(input: BookRequest, options?: RpcOptions): UnaryCall<BookRequest, BookItem>;
    /**
     * @generated from protobuf rpc: readBooks(bookStorePackage.Empty) returns (bookStorePackage.BooksList);
     */
    readBooks(input: Empty, options?: RpcOptions): UnaryCall<Empty, BooksList>;
}
/**
 * Our Book service definition.
 *
 * @generated from protobuf service bookStorePackage.BookService
 */
export class BookServiceClient implements IBookServiceClient, ServiceInfo {
    typeName = BookService.typeName;
    methods = BookService.methods;
    options = BookService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: createBook(bookStorePackage.BookItem) returns (bookStorePackage.BookItem);
     */
    createBook(input: BookItem, options?: RpcOptions): UnaryCall<BookItem, BookItem> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<BookItem, BookItem>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: readBook(bookStorePackage.BookRequest) returns (bookStorePackage.BookItem);
     */
    readBook(input: BookRequest, options?: RpcOptions): UnaryCall<BookRequest, BookItem> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<BookRequest, BookItem>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: readBooks(bookStorePackage.Empty) returns (bookStorePackage.BooksList);
     */
    readBooks(input: Empty, options?: RpcOptions): UnaryCall<Empty, BooksList> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, BooksList>("unary", this._transport, method, opt, input);
    }
}
