// @generated by protobuf-ts 2.9.4 with parameter add_pb_suffix,long_type_string,optimize_code_size
// @generated from protobuf file "helloworld.proto" (package "helloWorld", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message helloWorld.HelloRequest
 */
export interface HelloRequest {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
/**
 * @generated from protobuf message helloWorld.HelloReply
 */
export interface HelloReply {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class HelloRequest$Type extends MessageType<HelloRequest> {
    constructor() {
        super("helloWorld.HelloRequest", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message helloWorld.HelloRequest
 */
export const HelloRequest = new HelloRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HelloReply$Type extends MessageType<HelloReply> {
    constructor() {
        super("helloWorld.HelloReply", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message helloWorld.HelloReply
 */
export const HelloReply = new HelloReply$Type();
/**
 * @generated ServiceType for protobuf service helloWorld.Greeter
 */
export const Greeter = new ServiceType("helloWorld.Greeter", [
    { name: "SayHello", options: {}, I: HelloRequest, O: HelloReply }
]);
